<a href="https://colab.research.google.com/github/KarthikReddyvmd/Ethnotech-Data-Analytics-Training/blob/main/Machine-Learning/MachineLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Customer_Churn.xlsx to Customer_Churn (1).xlsx

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statistics
import seaborn as sns

In [ ]:
df = pd.read_excel('Customer_Churn.xlsx')

In [ ]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,One year,No,Mailed check,56.95,1889.5,0,0,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,0,0,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,3,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,0,0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,0,0,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,0,5,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,0,0,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,0,0,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,2,0,No

In [ ]:
df.loc[df['Churn'] == 'No', 'Churn'] = 0
df.loc[df['Churn'] == 'Yes', 'Churn'] = 1

In [ ]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0,0
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,One year,No,Mailed check,56.95,1889.5,0,0,0
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,0,0,1
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,3,0
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,0,0,0
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,0,5,0
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,0,0,0
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,0,0,1
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,2,0,0

In [ ]:
df['Churn'].value_counts()//len(df)*100

Churn
0    0
1    0
Name: count, dtype: int64

In [ ]:
x=df.drop(['customerID','Churn'],axis = 1)

In [ ]:
x

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,...,No,No,No,One year,No,Mailed check,56.95,1889.5,0,0
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,0,0
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,3
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,...,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,0,0
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,...,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,0,5
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,0,0
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,...,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,0,0
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,...,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,2,0

In [ ]:
y = df.Churn.values

In [ ]:
y

array([0, 0, 1, ..., 0, 1, 0], dtype=object)

In [ ]:
x.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'numAdminTickets', 'numTechTickets'],
      dtype='object')

In [ ]:
# CONVERT CATEGORICAL FEATURES TO NUMERICAL FEATURES

In [ ]:
x = pd.get_dummies(x, columns = ['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'] , drop_first = True)

In [ ]:
x

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,0,0,False,True,False,False,...,False,False,False,False,False,False,True,False,True,False
1,0,34,56.95,1889.5,0,0,True,False,False,True,...,False,False,False,False,True,False,False,False,False,True
2,0,2,53.85,108.15,0,0,True,False,False,True,...,False,False,False,False,False,False,True,False,False,True
3,0,45,42.30,1840.75,0,3,True,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,0,2,70.70,151.65,0,0,False,False,False,True,...,False,False,False,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,24,84.80,1990.5,0,0,True,True,True,True,...,False,True,False,True,True,False,True,False,False,True
7039,0,72,103.20,7362.9,0,5,False,True,True,True,...,False,True,False,True,True,False,True,True,False,False
7040,0,11,29.60,346.45,0,0,False,True,True,False,...,False,False,False,False,False,False,True,False,True,False
7041,1,4,74.40,306.6,0,0,True,True,False,True,...,False,False,False,False,False,False,True,False,False,True
7042,0,66,105.65,6844.5,2,0,True,False,False,True,...,False,True,False,True,False,True,True,False,False,False

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [ ]:
len(x_train)

5634

In [ ]:
len(x_test)

1409

In [ ]:
# Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

sc = StandardScaler()

# Convert 'TotalCharges' to numeric, handling errors by coercing non-numeric values to NaN
x_train['TotalCharges'] = pd.to_numeric(x_train['TotalCharges'], errors='coerce')
x_test['TotalCharges'] = pd.to_numeric(x_test['TotalCharges'], errors='coerce')

# Fill any NaN values introduced by coercion with 0
x_train['TotalCharges'] = x_train['TotalCharges'].fillna(0)
x_test['TotalCharges'] = x_test['TotalCharges'].fillna(0)

x_train_sc = sc.fit_transform(x_train)
x_test_sc = sc.transform(x_test)

In [ ]:
x_train_sc

array([[-0.4397627 ,  1.61253221,  0.67415397, ..., -0.51857393,
        -0.71219598,  1.82223822],
       [ 2.27395367, -0.7479074 , -0.61489382, ..., -0.51857393,
         1.4041079 , -0.54877567],
       [-0.4397627 ,  1.57183498, -1.3350973 , ..., -0.51857393,
        -0.71219598, -0.54877567],
       ...,
       [-0.4397627 ,  1.04277093, -1.46649701, ..., -0.51857393,
        -0.71219598,  1.82223822],
       [ 2.27395367, -1.27697145,  0.16352472, ..., -0.51857393,
         1.4041079 , -0.54877567],
       [-0.4397627 , -1.15487975, -1.47814002, ...,  1.92836536,
        -0.71219598, -0.54877567]])

In [ ]:
x_test_sc

array([[-0.4397627 , -0.54442123, -0.22069469, ..., -0.51857393,
         1.4041079 , -0.54877567],
       [-0.4397627 ,  1.1241654 ,  1.72202508, ...,  1.92836536,
        -0.71219598, -0.54877567],
       [-0.4397627 , -0.78860463,  0.23670937, ..., -0.51857393,
         1.4041079 , -0.54877567],
       ...,
       [ 2.27395367,  0.96137646,  1.56733934, ..., -0.51857393,
         1.4041079 , -0.54877567],
       [-0.4397627 , -0.58511846, -0.2855629 , ..., -0.51857393,
        -0.71219598,  1.82223822],
       [-0.4397627 , -1.27697145, -0.63318998, ..., -0.51857393,
        -0.71219598,  1.82223822]])

KNN - K Nearest Neighbours

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

# Convert y_train and y_test to integer type
y_train = y_train.astype(int)
y_test = y_test.astype(int)

model = KNeighborsClassifier(n_neighbors = 5)
model.fit(x_train_sc, y_train)

KNeighborsClassifier()

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
y_pred = model.predict(x_test_sc)
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[886 155]
 [127 241]]

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.85      0.86      1041
           1       0.61      0.65      0.63       368

    accuracy                           0.80      1409
   macro avg       0.74      0.75      0.75      1409
weighted avg       0.81      0.80      0.80      1409

In [ ]:
print(accuracy_score(y_test, y_pred))

0.7998580553584103

DECISION TREE

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model_dt = DecisionTreeClassifier()
model_dt.fit(x_train_sc, y_train)

DecisionTreeClassifier()

In [ ]:
y_pred = model_dt.predict(x_test_sc)
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[886 155]
 [113 255]]

In [ ]:
y_test

array([0, 0, 0, ..., 1, 0, 0])

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
y_pred = model_dt.predict(x_test_sc)
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[886 155]
 [113 255]]

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.85      0.87      1041
           1       0.62      0.69      0.66       368

    accuracy                           0.81      1409
   macro avg       0.75      0.77      0.76      1409
weighted avg       0.82      0.81      0.81      1409

In [ ]:
print(accuracy_score(y_test, y_pred))

0.8097941802696949

RANDOM FOREST

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier()
model_rf.fit(x_train_sc, y_train)

RandomForestClassifier()

In [ ]:
y_pred = model_rf.predict(x_test_sc)
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[946  95]
 [124 244]]

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
y_pred = model_rf.predict(x_test_sc)
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[946  95]
 [124 244]]

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.91      0.90      1041
           1       0.72      0.66      0.69       368

    accuracy                           0.84      1409
   macro avg       0.80      0.79      0.79      1409
weighted avg       0.84      0.84      0.84      1409

In [ ]:
print(accuracy_score(y_test, y_pred)*100)

84.45706174591909

BOOSTING

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
model_ab = AdaBoostClassifier()
model_ab.fit(x_train_sc, y_train)

AdaBoostClassifier()

In [ ]:
y_pred = model_ab.predict(x_test_sc)
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[945  96]
 [122 246]]

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.91      0.90      1041
           1       0.72      0.67      0.69       368

    accuracy                           0.85      1409
   macro avg       0.80      0.79      0.79      1409
weighted avg       0.84      0.85      0.84      1409

In [ ]:
print(accuracy_score(y_test, y_pred)*100)

84.52803406671399